---
title: "Part-II-Writeup"
author: "Team-FP03"
date: "12/10/2019"
output:
  pdf_document: default
  html_document:
    df_print: paged
header-includes: 
  \usepackage{float} 
  \floatplacement{figure}{H}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
suppressMessages(library(knitr))
suppressMessages(library(GGally))
suppressMessages(library(plyr))
suppressMessages(library(dplyr))
suppressMessages(library(mice))
suppressMessages(library(BAS))
```

```{r read-data}
load("paintings_train.Rdata")
load("paintings_test.Rdata")
load("paintings_validation.RData")
```

```{r}
# replace blank space and NA of categorical variables with n/a
paintings_train_new <- paintings_train
paintings_train_new[, c(4, 6:9, 12:22, 25, 27:28, 30:32, 34:59)] <- as.data.frame(sapply(paintings_train_new[, c(4, 6:9, 12:22, 25, 27:28, 30:32, 34:59)], function(x) ifelse(x == "" | x == "-", "n/a", x)))
```

```{r, include = FALSE}
# clean position
paintings_train_new <- paintings_train_new[-which(paintings_train_new$position > 1),]

# clean Shape
paintings_train_new[which(paintings_train_new$Shape == "ronde"), 28] <- "round"
paintings_train_new[which(paintings_train_new$Shape == "ovale"), 28] <- "oval"

# choose variables
paintings_train_new <- paintings_train_new %>% 
  select(-winningbidder, -authorstandard, -sale, -lot, -price, -count, -subject, -author, -Interm, -Surface_Rect, -Surface_Rnd, -material, -materialCat, -Height_in, -Width_in, -Diam_in)

# delete repeating data
paintings_train_new <- unique(paintings_train_new)

# imputate missing
set.seed(103)
imputed <- mice(paintings_train_new, m = 5)
paintings_train_new <- mice::complete(imputed)

# clean Surface
paintings_train_new <- paintings_train_new[-which(paintings_train_new$Surface == 0),]

# clean winningbiddertype
paintings_train_new$winningbiddertype <- case_when(
      paintings_train_new$winningbiddertype == "B" ~ "B",
      paintings_train_new$winningbiddertype == "BB" ~ "B",
      paintings_train_new$winningbiddertype == "BC" ~ "B",
      paintings_train_new$winningbiddertype == "C" ~ "C",
      paintings_train_new$winningbiddertype == "D" ~ "D",
      paintings_train_new$winningbiddertype == "DB" ~ "D",
      paintings_train_new$winningbiddertype == "DC" ~ "D",
      paintings_train_new$winningbiddertype == "DD" ~ "D",
      paintings_train_new$winningbiddertype == "E" ~ "E",
      paintings_train_new$winningbiddertype == "EB" ~ "E",
      paintings_train_new$winningbiddertype == "EBC" ~ "E",
      paintings_train_new$winningbiddertype == "EC" ~ "E",
      paintings_train_new$winningbiddertype == "ED" ~ "E",
      paintings_train_new$winningbiddertype == "U" ~ "n/a",
      paintings_train_new$winningbiddertype == "n/a" ~ "n/a"
    )
paintings_train_new$winningbiddertype <- as.factor(paintings_train_new$winningbiddertype)
paintings_train_new$logprice <- floor(paintings_train_new$logprice)
```

```{r fig.cap = "Variable Importance Measures in Random Forests"}
# log transformation to Surface
paintings_train_new$Surface <- log(paintings_train_new$Surface)
colnames(paintings_train_new)[15] <- "log_Surface"
```

```{r cache = TRUE}
set.seed(3)
bma <- bas.lm(logprice ~ dealer + year + origin_author + endbuyer + log_Surface + finished + lrgfont + position + type_intermed + winningbiddertype, paintings_train_new,
              prior="g-prior", alpha = dim(paintings_train_new)[1],
              modelprior=uniform(), method="MCMC", MCMC.iterations = 100000)
plot(bma)
```

```{r cache = TRUE, warning=FALSE}
# full model
model_test <- lm(logprice ~ (dealer + year + origin_author + endbuyer + log_Surface + finished + lrgfont + type_intermed)^2, data = paintings_train_new)

# bma
set.seed(3)
bma2 <- bas.lm(formula(model_test), paintings_train_new,
               prior = "JZS", modelprior = uniform(),
               method = "MCMC", MCMC.iterations = 100000)

```

```{r predict-model1, echo = FALSE, warning = FALSE, include = FALSE}
# test data
paintings_test_new <- paintings_test

# replace blank space and NA of categorical variables with n/a
paintings_test_new[, c(4, 6:9, 12:22, 25, 27:28, 30:32, 34:59)] <- as.data.frame(
  sapply(paintings_test_new[, c(4, 6:9, 12:22, 25, 27:28, 30:32, 34:59)],
         function(x) ifelse(paste(x) == "" | paste(x) == "-",
                            "n/a", paste(x))))

# clean position
paintings_test_new[which(paintings_test_new$position > 1), 3] <-
  paintings_test_new[which(paintings_test_new$position > 1), 3]/100

# clean Shape
paintings_test_new[which(paintings_test_new$Shape == "ronde"), 28] <-
  "round"
paintings_test_new[which(paintings_test_new$Shape == "ovale"), 28] <-
  "oval"

# choose variables
paintings_test_new <- paintings_test_new %>% 
  select(-winningbidder, -authorstandard, -sale, -lot, -price, -count,
         -subject, -author, -Interm, -Height_in, -Width_in, -Diam_in,
         -Surface_Rect, -Surface_Rnd, -material, -materialCat)

# clean Surface
paintings_test_new[which(paintings_test_new$Surface == 0), 15] <- NA

# imputate missing
set.seed(103)
imputed_test <- mice(paintings_test_new, m = 5)
paintings_test_new <- mice::complete(imputed_test)

# log transformation to Surface
paintings_test_new$Surface <- log(paintings_test_new$Surface)
colnames(paintings_test_new)[15] <- "log_Surface"

# clean winningbiddertype
paintings_test_new$winningbiddertype <- case_when(
      paintings_test_new$winningbiddertype == "B" ~ "B",
      paintings_test_new$winningbiddertype == "BB" ~ "B",
      paintings_test_new$winningbiddertype == "BC" ~ "B",
      paintings_test_new$winningbiddertype == "C" ~ "C",
      paintings_test_new$winningbiddertype == "D" ~ "D",
      paintings_test_new$winningbiddertype == "DB" ~ "D",
      paintings_test_new$winningbiddertype == "DC" ~ "D",
      paintings_test_new$winningbiddertype == "DD" ~ "D",
      paintings_test_new$winningbiddertype == "E" ~ "E",
      paintings_test_new$winningbiddertype == "EB" ~ "E",
      paintings_test_new$winningbiddertype == "EBC" ~ "E",
      paintings_test_new$winningbiddertype == "EC" ~ "E",
      paintings_test_new$winningbiddertype == "ED" ~ "E",
      paintings_test_new$winningbiddertype == "U" ~ "n/a",
      paintings_test_new$winningbiddertype == "n/a" ~ "n/a"
    )
paintings_test_new$winningbiddertype <- as.factor(paintings_test_new$winningbiddertype)
```

```{r warning=FALSE}
MPM <- predict(bma2, estimator = "MPM")
variable.names(MPM)
```

```{r}
lm.BPM <- lm(logprice ~ dealer + year + origin_author + endbuyer + log_Surface + finished
             + lrgfont + type_intermed + year:endbuyer, data = paintings_train_new)
```

```{r}
predictions <- as.data.frame(exp(predict(lm.BPM, paintings_test_new,
                                         interval = "pred")))
save(predictions, file="predict-test.Rdata")
```

```{r}
lm2 <- lm(logprice ~ (year + dealer + log_Surface + finished + lrgfont)^2, data = paintings_train_new)
bic <- step(lm2, step = log(nobs(lm2)), trace = F)
summary(bic)
lm.bic5 <- lm(logprice ~ year + dealer + log_Surface + finished + lrgfont
              + year:dealer + year:log_Surface + log_Surface:finished 
              + log_Surface:lrgfont, data = paintings_train_new)
predictions <- as.data.frame(exp(predict(lm.bic5, paintings_test_new,
                                         interval = "pred")))
save(predictions, file="predict-test.Rdata")
```

```{r predict-model-final, cache=TRUE, echo=FALSE, include=FALSE}
# change model1 or update as needed
bma3 <- bas.lm(formula(lm.BPM), paintings_train_new,
               prior = "JZS", modelprior = uniform(),
               method = "MCMC", MCMC.iterations = 100000)
predictions <- predict(bma3, newdata = paintings_test_new, se.fit = TRUE)
```

```{r output-test, echo=FALSE, include=FALSE}
fit <- exp(predictions$fit)
lwr <- exp(predictions$fit - 1.96 * predictions$se.bma.pred)
upr <- exp(predictions$fit + 1.96 * predictions$se.bma.pred)
predictions <- data.frame(fit, lwr, upr)
save(predictions, file="predict-test.Rdata")
```

```{r predict-model2, echo = FALSE, warning = FALSE, include = FALSE}
# test data
paintings_val_new <- paintings_validation

# replace blank space and NA of categorical variables with n/a
paintings_val_new[, c(4, 6:9, 12:22, 25, 27:28, 30:32, 34:59)] <- as.data.frame(
  sapply(paintings_val_new[, c(4, 6:9, 12:22, 25, 27:28, 30:32, 34:59)],
         function(x) ifelse(paste(x) == "" | paste(x) == "-",
                            "n/a", paste(x))))

# clean position
paintings_val_new[which(paintings_val_new$position > 1), 3] <-
  paintings_val_new[which(paintings_val_new$position > 1), 3]/100

# clean Shape
paintings_val_new[which(paintings_val_new$Shape == "ronde"), 28] <-
  "round"
paintings_val_new[which(paintings_val_new$Shape == "ovale"), 28] <-
  "oval"

# choose variables
paintings_val_new <- paintings_val_new %>% 
  select(-winningbidder, -authorstandard, -sale, -lot, -price, -count,
         -subject, -author, -Interm, -Height_in, -Width_in, -Diam_in,
         -Surface_Rect, -Surface_Rnd, -material, -materialCat)

# clean Surface
paintings_val_new[which(paintings_val_new$Surface == 0), 15] <- NA

# imputate missing
set.seed(103)
imputed_val <- mice(paintings_val_new, m = 5)
paintings_val_new <- mice::complete(imputed_val)

# log transformation to Surface
paintings_val_new$Surface <- log(paintings_val_new$Surface)
colnames(paintings_val_new)[15] <- "log_Surface"

# clean winningbiddertype
paintings_val_new$winningbiddertype <- case_when(
      paintings_val_new$winningbiddertype == "B" ~ "B",
      paintings_val_new$winningbiddertype == "BB" ~ "B",
      paintings_val_new$winningbiddertype == "BC" ~ "B",
      paintings_val_new$winningbiddertype == "C" ~ "C",
      paintings_val_new$winningbiddertype == "D" ~ "D",
      paintings_val_new$winningbiddertype == "DB" ~ "D",
      paintings_val_new$winningbiddertype == "DC" ~ "D",
      paintings_val_new$winningbiddertype == "DD" ~ "D",
      paintings_val_new$winningbiddertype == "E" ~ "E",
      paintings_val_new$winningbiddertype == "EB" ~ "E",
      paintings_val_new$winningbiddertype == "EBC" ~ "E",
      paintings_val_new$winningbiddertype == "EC" ~ "E",
      paintings_val_new$winningbiddertype == "ED" ~ "E",
      paintings_val_new$winningbiddertype == "U" ~ "n/a",
      paintings_val_new$winningbiddertype == "n/a" ~ "n/a"
    )
paintings_val_new$winningbiddertype <- as.factor(paintings_val_new$winningbiddertype)
```

```{r predict-model-val, cache=TRUE, echo=FALSE, include=FALSE}
# change model1 or update as needed
predictions <- predict(bma, newdata = paintings_val_new, se.fit = TRUE)
```

```{r output-val, echo=FALSE, include=FALSE}
fit <- exp(predictions$fit)
lwr <- exp(predictions$fit - 1.96 * predictions$se.bma.pred)
upr <- exp(predictions$fit + 1.96 * predictions$se.bma.pred)
predictions <- data.frame(fit, lwr, upr)
save(predictions, file="predict-validation.Rdata")
```
